version: '3.7'

services:
  frontend:
    build:
      context: ./frontend1
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
