# Generated by Django 4.2.14 on 2024-07-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admiral', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='business_expansion.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('Recruit', 'Recruit'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Commander', 'Commander'), ('Admiral', 'Admiral')], max_length=20)),
                ('stationed_currently', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew', to='business_expansion.ship')),
                ('stationed_past', models.ManyToManyField(blank=True, related_name='former_crew', to='business_expansion.ship')),
            ],
        ),
    ]
