# Generated by Django 4.2.14 on 2024-07-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_expansion', '0002_remove_fleet_size_remove_ship_fleet_remove_ship_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='fleet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship', to='business_expansion.fleet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stationed_currently',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew', to='business_expansion.ship'),
        ),
    ]
