# Generated by Django 4.2.14 on 2024-07-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_expansion', '0003_ship_fleet_alter_person_stationed_currently'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='ships',
        ),
    ]
